version: "3.2"
services:
  nginx: 
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shared
  auth-service:
    image: php:7.4-apache
    volumes:
      - ./index.php:/var/www/html/index.php:ro
    environment:
      - ALLOWED_PASSPHRASE=topsecret
    networks:
      - shared

networks:
  shared:
